<html>

<head>
<title>骚熊音乐->用户登陆</title>
<link rel="stylesheet" type="text/css" href="css/style.css">
</head>

<body topmargin="0" leftmargin="0" bgcolor="#000000" >
<div align="center"><center>
<table border="0" cellspacing="1" width="90%">
  <tr>
    <td>
    <form method="post" action="user_login_reg.asp">
      <table width="45%" border="1" cellspacing="0" cellpadding="1" align="center">
        <tr>
          <td><table width="100%" border="0" cellspacing="1" cellpadding="1">
            <tr>
              <td width="33%" align="center" height="30" colspan="2"><a name="注册">我要注册</a></td>
            </tr>
            <tr>
              <td width="33%" align="right" height="30">用户名：</td>
              <td width="67%"><input style="BORDER-BOTTOM: #000000;font-size:9pt; 1px solid; BORDER-LEFT: #000000 1px solid; BORDER-RIGHT: #000000 1px solid; BORDER-TOP: #000000 1px solid; COLOR: #800000" type="text" name="username" maxlength="20" size="20"> </td>
            </tr>
            <tr>
              <td width="33%" align="right" height="30">密 码：</td>
              <td width="67%"><input style="BORDER-BOTTOM: #000000;font-size:9pt; 1px solid; BORDER-LEFT: #000000 1px solid; BORDER-RIGHT: #000000 1px solid; BORDER-TOP: #000000 1px solid; COLOR: #800000" type="password" name="password" maxlength="16" size="20"> </td>
            </tr>
            <tr>
              <td colspan="2" height="15"></td>
            </tr>
          </table>
          </td>
        </tr>
        <tr align="center">
          <td height="40">
                  <input style="background-color: #CCCCCC;font-size:9pt; border: 1 solid #000000" type="submit" name="Submit" value="注册"> 
          &nbsp; 
                  <input style="background-color: #CCCCCC;font-size:9pt; border: 1 solid #000000" type="reset" name="Submit2" value="重写">
                   </td>
        </tr>
      </table>
    </form>
    </td>
  </tr>

  <tr>
    <td vAlign="top"><br>
    <table align="center">
      <tr>
        <td><p align="center"><a name="条款">条款规定</a></p>
        <p>1. 不得将本曲库的任何内容用于商业活动。<br>
        2. 不得发表反动、不健康等违反法律的言论。<br>
        3. 不要发表于音乐无关的言论。<br>
        4. 互相尊重，对自己的言论和行为负责。 <br>
        5. 版主PengJohn保留一切权力。<br>
        </td>
      </tr>
    </table>
    </td>
  </tr>

</table>
<br><br><br><br><br><br><br><br><br>
<br><br><br><br><br><br><br><br><br>
</center></div>
</body>
</html>
